name: "🐛 Bug Report for Unity"
description: 提交一个Puer for Unity的问题 / Report a bug in puer for Unity
title: "[Unity] Bug: "
labels: ["bug", "Unity"]
assignees:
  - chexiongsheng
body:
  - type: checkboxes
    id: read
    attributes:
      label: 前置阅读 | Pre-reading
      description: 我已经自行查找、阅读以下内容（**阅读了请打勾**） | I have searched and read the following on my own (**Please tick after reading**)
      options:
        - label: "[文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)"
          required: true
        - label: "[Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)"
          required: true
        - label: "[FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)"
          required: true
  - type: input
    id: puer-version
    attributes:
      label: Puer的版本 | Puer Version
      placeholder: 
    validations:
      required: true
  - type: input
    id: ue-version
    attributes:
      label: Unity的版本 | Unity Version
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 发生在哪个平台 | Platform
      options:
        - Editor(mac)
        - Editor(win)
        - Android
        - Android simluator
        - iOS
        - iOS simulator
        - mac
        - win
        - All
        - Other
    validations:
      required: true
  - type: textarea
    id: message
    attributes:
      label: 错误信息 | Error Message
      description: 请附上你得到的错误信息，必要时附图 | Please fill this textarea with your error message.
  - type: textarea
    id: reproduce
    attributes:
      label: 问题重现 | Bug reproduce
      description: 请复述Bug重现流程，必要时附图 | Please tell me the bug reproduction process, attach pictures if necessary
    validations:
      required: true
