/*
* Tencent is pleased to support the open source community by making Puerts available.
* Copyright (C) 2020 Tencent.  All rights reserved.
* Puerts is licensed under the BSD 3-Clause License, except for the third-party components listed in the file 'LICENSE' which may be subject to their corresponding license terms.
* This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this source code package.
*/

#if PUERTS_DISABLE_IL2CPP_OPTIMIZATION || !ENABLE_IL2CPP

using System;
using System.Text;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Collections.Generic;

namespace Puerts
{
    /// <summary>
    /// Generates static C# wrapper code for a given type by:
    /// 1. Building Expression Trees via ExpressionsWrap (without compiling)
    /// 2. Translating them to C# source code via ExpressionToCSharpVisitor
    /// </summary>
    public static class StaticWrapperGenerator
    {
        /// <summary>
        /// Information about a generated wrapper member.
        /// </summary>
        public class WrapperMemberInfo
        {
            public string Name;
            public bool IsStatic;
            public string MemberType; // "Method", "Constructor", "Property", "Field"
            public string WrapperMethodName;
            public string SetterMethodName; // For Property/Field: the setter wrapper method name
        }

        /// <summary>
        /// Result of generating a wrapper for a single type.
        /// </summary>
        public class TypeWrapperResult
        {
            public Type Type;
            public string SourceCode;
            public string ClassName;
            public List<WrapperMemberInfo> Members = new List<WrapperMemberInfo>();
        }

        private static bool ParameterTypeNotAcceptable(Type type)
        {
            if (type.IsByRef && type.GetElementType().IsByRefLike()) return true;
            // Check if the type (or its element type for ByRef/Array) is not publicly accessible
            var checkType = type.IsByRef ? type.GetElementType() : type;
            if (checkType.IsArray) checkType = checkType.GetElementType();
            if (checkType != null && !checkType.IsPublic && !checkType.IsNestedPublic) return true;
            return type == typeof(TypedReference) || type.IsPointer || (type.IsValueType && !type.IsPrimitive && type.IsByRefLike());
        }

        private static bool ReturnTypeNotAcceptable(Type type)
        {
            return ParameterTypeNotAcceptable(type) || type.IsByRef;
        }

        /// <summary>
        /// Generates a static wrapper .cs file content for the given type.
        /// </summary>
        public static TypeWrapperResult GenerateWrapperForType(Type type, Func<MemberInfo, bool> filter = null)
        {
            var result = new TypeWrapperResult
            {
                Type = type,
                ClassName = GetWrapperClassName(type)
            };

            var sb = new StringBuilder();
            var visitor = new ExpressionToCSharpVisitor();

            // File header
            sb.AppendLine("// Auto-generated by PuerTS StaticWrapper Generator. DO NOT EDIT.");
            sb.AppendLine($"// Source type: {ExpressionToCSharpVisitor.GetTypeName(type)}");
            sb.AppendLine();
            sb.AppendLine("#if PUERTS_DISABLE_IL2CPP_OPTIMIZATION || !ENABLE_IL2CPP");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine();
            sb.AppendLine("namespace PuertsStaticWrap");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {result.ClassName}");
            sb.AppendLine("    {");

            // Collect all static fields needed by the visitor
            var allStaticFields = new List<ExpressionToCSharpVisitor.StaticFieldInfo>();

            BindingFlags flag = BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public;

            // --- Fields ---
            FieldInfo[] fieldInfos = type.GetFields(flag);
            foreach (var fieldInfo in fieldInfos)
            {
                try
                {
                    if (ReturnTypeNotAcceptable(fieldInfo.FieldType)) continue;
                    // Skip obsolete fields (including warning level)
                    var fieldObsolete = fieldInfo.GetCustomAttribute<ObsoleteAttribute>(false);
                    if (fieldObsolete != null) continue;
                    if (filter != null && filter(fieldInfo)) continue;

                    // Field getter
                    var getterExpr = ExpressionsWrap.BuildFieldGetterExpression(fieldInfo);
                    string getterMethodName = SanitizeMethodName($"g_{fieldInfo.Name}");
                    EmitWrapperMethod(sb, visitor, getterExpr, getterMethodName,
                        $"Field getter for {ExpressionToCSharpVisitor.GetTypeName(type)}.{fieldInfo.Name}",
                        "pesapi_callback", allStaticFields);

                    var fieldMemberInfo = new WrapperMemberInfo
                    {
                        Name = fieldInfo.Name,
                        IsStatic = fieldInfo.IsStatic,
                        MemberType = "Field",
                        WrapperMethodName = getterMethodName
                    };

                    // Field setter (if not readonly)
                    if (!fieldInfo.IsInitOnly && !fieldInfo.IsLiteral)
                    {
                        var setterExpr = ExpressionsWrap.BuildFieldSetterExpression(fieldInfo);
                        string setterMethodName = SanitizeMethodName($"s_{fieldInfo.Name}");
                        EmitWrapperMethod(sb, visitor, setterExpr, setterMethodName,
                            $"Field setter for {ExpressionToCSharpVisitor.GetTypeName(type)}.{fieldInfo.Name}",
                            "pesapi_callback", allStaticFields);
                        fieldMemberInfo.SetterMethodName = setterMethodName;
                    }

                    result.Members.Add(fieldMemberInfo);
                }
                catch (Exception e)
                {
                    sb.AppendLine($"        // SKIPPED: Field {fieldInfo.Name} — {EscapeComment(e.Message)}");
                    sb.AppendLine();
                }
            }

            // --- Methods (including properties and extension methods) ---
            var methodInfos = type.GetMethods(flag | BindingFlags.NonPublic).ToList();

            // Add extension methods
            var extensionMethods = Puerts.ExtensionMethodInfo.Get(type.AssemblyQualifiedName);
            if (extensionMethods != null && extensionMethods.Length > 0)
            {
                foreach (var extensionMethod in extensionMethods)
                {
                    var method = extensionMethod;
                    if (method.IsGenericMethodDefinition)
                    {
                        var genericArguments = method.GetGenericArguments();
                        var constraintedArgumentTypes = new Type[genericArguments.Length];
                        for (var j = 0; j < genericArguments.Length; j++)
                        {
                            constraintedArgumentTypes[j] = genericArguments[j].BaseType;
                        }
                        method = method.MakeGenericMethod(constraintedArgumentTypes);
                    }
                    methodInfos.Add(method);
                }
            }

            // Group methods by name and static/instance
            var methodGroups = new Dictionary<string, List<MethodInfo>>();
            var propertyGetters = new Dictionary<string, MethodInfo>();
            var propertySetters = new Dictionary<string, MethodInfo>();

            foreach (var methodInfo in methodInfos)
            {
                if (methodInfo.IsGenericMethodDefinition) continue;
                if (methodInfo.GetParameters().Any(pi => ParameterTypeNotAcceptable(pi.ParameterType)) || ReturnTypeNotAcceptable(methodInfo.ReturnType)) continue;
                var clsCompliant = methodInfo.GetCustomAttribute<CLSCompliantAttribute>(false);
                if (clsCompliant != null && !clsCompliant.IsCompliant) continue;
                // Skip methods whose declaring type is not publicly accessible (e.g. internal extension methods)
                if (methodInfo.DeclaringType != null && !methodInfo.DeclaringType.IsPublic && !methodInfo.DeclaringType.IsNestedPublic
                    && methodInfo.DeclaringType != type) continue;
                // Skip obsolete members (including warning level)
                var obsoleteAttr = methodInfo.GetCustomAttribute<ObsoleteAttribute>(false);
                if (obsoleteAttr != null) continue;
                if (filter != null && filter(methodInfo)) continue;

                string methodName = methodInfo.Name;
                if (!methodInfo.IsPublic)
                {
                    int dotPos = methodName.LastIndexOf('.');
                    if (dotPos == -1) continue;
                    methodName = methodName.Substring(dotPos + 1);
                }

                if (methodInfo.IsSpecialName && methodName.StartsWith("get_") && methodInfo.GetParameters().Length == 0)
                {
                    string propName = methodName.Substring(4);
                    // Check if the property itself is obsolete (including warning level)
                    var propInfo = type.GetProperty(propName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly);
                    var propObsolete = propInfo?.GetCustomAttribute<ObsoleteAttribute>(false);
                    if (propObsolete != null) continue;
                    string key = (methodInfo.IsStatic ? "s_" : "i_") + propName;
                    propertyGetters[key] = methodInfo;
                }
                else if (methodInfo.IsSpecialName && methodName.StartsWith("set_") && methodInfo.GetParameters().Length == 1)
                {
                    string propName = methodName.Substring(4);
                    // Check if the property itself is obsolete (including warning level)
                    var propInfo = type.GetProperty(propName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly);
                    var propObsolete = propInfo?.GetCustomAttribute<ObsoleteAttribute>(false);
                    if (propObsolete != null) continue;
                    string key = (methodInfo.IsStatic ? "s_" : "i_") + propName;
                    propertySetters[key] = methodInfo;
                }
                else
                {
                    bool isExtension = Puerts.ExtensionMethodInfo.GetExtendedType(methodInfo) == type;
                    string groupKey = (methodInfo.IsStatic && !isExtension ? "s_" : "i_") + methodName;
                    if (!methodGroups.ContainsKey(groupKey))
                        methodGroups[groupKey] = new List<MethodInfo>();
                    methodGroups[groupKey].Add(methodInfo);
                }
            }

            // Emit property wrappers
            var allPropKeys = new HashSet<string>(propertyGetters.Keys);
            foreach (var k in propertySetters.Keys) allPropKeys.Add(k);

            foreach (var key in allPropKeys)
            {
                bool isStatic = key.StartsWith("s_");
                string propName = key.Substring(2);

                if (propertyGetters.TryGetValue(key, out var getter))
                {
                    try
                    {
                        var getterExpr = ExpressionsWrap.BuildMethodWrapExpression(type, getter, false);
                        string getterMethodName = SanitizeMethodName($"pg_{propName}" + (isStatic ? "_s" : ""));
                        EmitWrapperMethod(sb, visitor, getterExpr, getterMethodName,
                            $"Property getter for {ExpressionToCSharpVisitor.GetTypeName(type)}.{propName}",
                            "pesapi_callback", allStaticFields);

                        var propMemberInfo = new WrapperMemberInfo
                        {
                            Name = propName,
                            IsStatic = isStatic,
                            MemberType = "Property",
                            WrapperMethodName = getterMethodName
                        };

                        // Try to generate setter inline so we can record SetterMethodName
                        if (propertySetters.TryGetValue(key, out var setterInline))
                        {
                            try
                            {
                                var setterExpr = ExpressionsWrap.BuildMethodWrapExpression(type, setterInline, false);
                                string setterMethodName = SanitizeMethodName($"ps_{propName}" + (isStatic ? "_s" : ""));
                                EmitWrapperMethod(sb, visitor, setterExpr, setterMethodName,
                                    $"Property setter for {ExpressionToCSharpVisitor.GetTypeName(type)}.{propName}",
                                    "pesapi_callback", allStaticFields);
                                propMemberInfo.SetterMethodName = setterMethodName;
                            }
                            catch (Exception e)
                            {
                                sb.AppendLine($"        // SKIPPED: Property setter {propName} — {EscapeComment(e.Message)}");
                                sb.AppendLine();
                            }
                        }

                        result.Members.Add(propMemberInfo);
                    }
                    catch (Exception e)
                    {
                        sb.AppendLine($"        // SKIPPED: Property getter {propName} — {EscapeComment(e.Message)}");
                        sb.AppendLine();

                        // Even if getter failed, try setter alone
                        if (propertySetters.TryGetValue(key, out var setterFallback))
                        {
                            try
                            {
                                var setterExpr = ExpressionsWrap.BuildMethodWrapExpression(type, setterFallback, false);
                                string setterMethodName = SanitizeMethodName($"ps_{propName}" + (isStatic ? "_s" : ""));
                                EmitWrapperMethod(sb, visitor, setterExpr, setterMethodName,
                                    $"Property setter for {ExpressionToCSharpVisitor.GetTypeName(type)}.{propName}",
                                    "pesapi_callback", allStaticFields);
                            }
                            catch (Exception e2)
                            {
                                sb.AppendLine($"        // SKIPPED: Property setter {propName} — {EscapeComment(e2.Message)}");
                                sb.AppendLine();
                            }
                        }
                    }
                }
                else if (propertySetters.TryGetValue(key, out var setterOnly))
                {
                    // No getter, only setter
                    try
                    {
                        var setterExpr = ExpressionsWrap.BuildMethodWrapExpression(type, setterOnly, false);
                        string setterMethodName = SanitizeMethodName($"ps_{propName}" + (isStatic ? "_s" : ""));
                        EmitWrapperMethod(sb, visitor, setterExpr, setterMethodName,
                            $"Property setter for {ExpressionToCSharpVisitor.GetTypeName(type)}.{propName}",
                            "pesapi_callback", allStaticFields);

                        result.Members.Add(new WrapperMemberInfo
                        {
                            Name = propName,
                            IsStatic = isStatic,
                            MemberType = "Property",
                            SetterMethodName = setterMethodName
                        });
                    }
                    catch (Exception e)
                    {
                        sb.AppendLine($"        // SKIPPED: Property setter {propName} — {EscapeComment(e.Message)}");
                        sb.AppendLine();
                    }
                }
            }

            // Emit method wrappers
            foreach (var kv in methodGroups)
            {
                bool isStatic = kv.Key.StartsWith("s_");
                string methodName = kv.Key.Substring(2);

                try
                {
                    var methodExpr = ExpressionsWrap.BuildMethodWrapExpression(type, kv.Value.ToArray(), false);
                    string wrapperMethodName = SanitizeMethodName($"m_{methodName}" + (isStatic ? "_s" : ""));
                    EmitWrapperMethod(sb, visitor, methodExpr, wrapperMethodName,
                        $"Wrapper for {ExpressionToCSharpVisitor.GetTypeName(type)}.{methodName}({kv.Value.Count} overload(s))",
                        "pesapi_callback", allStaticFields);

                    result.Members.Add(new WrapperMemberInfo
                    {
                        Name = methodName,
                        IsStatic = isStatic,
                        MemberType = "Method",
                        WrapperMethodName = wrapperMethodName
                    });
                }
                catch (Exception e)
                {
                    sb.AppendLine($"        // SKIPPED: Method {methodName} — {EscapeComment(e.Message)}");
                    sb.AppendLine();
                }
            }

            // --- Constructor ---
            try
            {
                if (typeof(MulticastDelegate).IsAssignableFrom(type) && type != typeof(MulticastDelegate))
                {
                    var ctorExpr = ExpressionsWrap.BuildDelegateConstructorWrapExpression(type, type.GetConstructors(), false);
                    EmitWrapperMethod(sb, visitor, ctorExpr, "ctor",
                        $"Delegate constructor for {ExpressionToCSharpVisitor.GetTypeName(type)}",
                        "pesapi_constructor", allStaticFields);

                    result.Members.Add(new WrapperMemberInfo
                    {
                        Name = ".ctor",
                        IsStatic = true,
                        MemberType = "Constructor",
                        WrapperMethodName = "ctor"
                    });
                }
                else
                {
                    var ctors = type.GetConstructors()
                        .Where(ctorInfo => !ctorInfo.GetParameters().Any(pi => ParameterTypeNotAcceptable(pi.ParameterType)))
                        .ToArray();
                    if (ctors.Length > 0 || type.IsValueType)
                    {
                        var ctorExpr = ExpressionsWrap.BuildConstructorWrapExpression(type, ctors, false);
                        EmitWrapperMethod(sb, visitor, ctorExpr, "ctor",
                            $"Constructor for {ExpressionToCSharpVisitor.GetTypeName(type)}",
                            "pesapi_constructor", allStaticFields);

                        result.Members.Add(new WrapperMemberInfo
                        {
                            Name = ".ctor",
                            IsStatic = true,
                            MemberType = "Constructor",
                            WrapperMethodName = "ctor"
                        });
                    }
                }
            }
            catch (Exception e)
            {
                sb.AppendLine($"        // SKIPPED: Constructor — {EscapeComment(e.Message)}");
                sb.AppendLine();
            }

            // Emit static field declarations (for MethodInfo/FieldInfo constants etc.)
            if (allStaticFields.Count > 0)
            {
                sb.AppendLine("        #region Static Field Initializers");
                sb.AppendLine();
                foreach (var field in allStaticFields)
                {
                    sb.AppendLine($"        private static readonly {ExpressionToCSharpVisitor.GetTypeName(field.FieldType)} {field.FieldName} = {field.InitializerCode};");
                }
                sb.AppendLine();
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("#endif");

            result.SourceCode = sb.ToString();
            return result;
        }

        private static void EmitWrapperMethod(
            StringBuilder sb,
            ExpressionToCSharpVisitor visitor,
            LambdaExpression lambdaExpr,
            string methodName,
            string comment,
            string delegateType,
            List<ExpressionToCSharpVisitor.StaticFieldInfo> allStaticFields)
        {
            sb.AppendLine($"        // {comment}");

            // Translate the Expression Tree to C# source code
            string body = visitor.Translate(lambdaExpr.Body);

            // Collect static fields from this translation
            allStaticFields.AddRange(visitor.StaticFields);

            // Determine return type
            string returnType = delegateType == "pesapi_constructor" ? "System.IntPtr" : "void";

            // Emit method signature
            sb.AppendLine($"        public static {returnType} {methodName}(System.IntPtr apis, System.IntPtr info)");

            // Emit method body
            sb.AppendLine("        {");

            // The translated body is a block expression — we need to inline its contents
            // The visitor outputs the block with { }, so we need to adjust indentation
            // Body content is inside the method's { }, so it needs 3 levels of indentation (12 spaces)
            string[] lines = body.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
            foreach (var line in lines)
            {
                if (string.IsNullOrWhiteSpace(line)) continue;
                sb.Append("            ");
                sb.AppendLine(line);
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// <summary>
        /// Generates the registration class that registers all static wrappers.
        /// </summary>
        public static string GenerateRegisterInfo(IEnumerable<TypeWrapperResult> wrapperResults)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by PuerTS StaticWrapper Generator. DO NOT EDIT.");
            sb.AppendLine();
            sb.AppendLine("#if PUERTS_DISABLE_IL2CPP_OPTIMIZATION || !ENABLE_IL2CPP");
            sb.AppendLine();
            sb.AppendLine("using Puerts;");
            sb.AppendLine("using Puerts.TypeMapping;");
            sb.AppendLine();
            sb.AppendLine("namespace PuertsStaticWrap");
            sb.AppendLine("{");
            sb.AppendLine("#if !PUERTS_GENERAL");
            sb.AppendLine("    [UnityEngine.Scripting.Preserve]");
            sb.AppendLine("#endif");
            sb.AppendLine("    public static class PuerRegisterInfo_Gen");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void AddRegisterInfoGetterIntoScriptEnv(ScriptEnv scriptEnv)");
            sb.AppendLine("        {");

            foreach (var wrapper in wrapperResults)
            {
                if (wrapper.Members.Count == 0) continue;

                string typeName = ExpressionToCSharpVisitor.GetTypeName(wrapper.Type);
                string className = wrapper.ClassName;

                sb.AppendLine($"            scriptEnv.AddRegisterInfoGetter(typeof({typeName}), () =>");
                sb.AppendLine("            {");
                sb.AppendLine("                return new RegisterInfo");
                sb.AppendLine("                {");
                sb.AppendLine("                    Members = new System.Collections.Generic.Dictionary<string, MemberRegisterInfo>");
                sb.AppendLine("                    {");

                var emittedKeys = new HashSet<string>();
                foreach (var member in wrapper.Members)
                {
                    string memberType = member.MemberType == "Constructor" ? "MemberType.Constructor" :
                                        member.MemberType == "Method" ? "MemberType.Method" :
                                        "MemberType.Property";

                    // Static members need a '_static' suffix in the key to avoid collisions
                    // with instance members of the same name (e.g. Vector3.Scale)
                    string dictKey = member.IsStatic ? $"{member.Name}_static" : member.Name;

                    // Skip duplicate keys (can happen when a property and extension method have the same name)
                    if (!emittedKeys.Add(dictKey)) continue;

                    // Build callback assignments
                    var callbackParts = new List<string>();
                    switch (member.MemberType)
                    {
                        case "Constructor":
                            if (!string.IsNullOrEmpty(member.WrapperMethodName))
                                callbackParts.Add($"ConstructorCallback = new pesapi_constructor({className}.{member.WrapperMethodName})");
                            break;
                        case "Method":
                            if (!string.IsNullOrEmpty(member.WrapperMethodName))
                                callbackParts.Add($"Callback = new pesapi_callback({className}.{member.WrapperMethodName})");
                            break;
                        case "Property":
                        case "Field":
                            if (!string.IsNullOrEmpty(member.WrapperMethodName))
                                callbackParts.Add($"GetterCallback = new pesapi_callback({className}.{member.WrapperMethodName})");
                            if (!string.IsNullOrEmpty(member.SetterMethodName))
                                callbackParts.Add($"SetterCallback = new pesapi_callback({className}.{member.SetterMethodName})");
                            break;
                    }
                    string callbackStr = callbackParts.Count > 0 ? ", " + string.Join(", ", callbackParts) : "";

                    sb.AppendLine($"                        {{ \"{dictKey}\", new MemberRegisterInfo {{ Name = \"{member.Name}\", IsStatic = {(member.IsStatic ? "true" : "false")}, MemberType = {memberType}, UseBindingMode = BindingMode.FastBinding{callbackStr} }} }},");
                }

                sb.AppendLine("                    }");
                sb.AppendLine("                };");
                sb.AppendLine("            });");
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("#endif");

            return sb.ToString();
        }

        /// <summary>
        /// Gets a safe wrapper class name for the given type.
        /// </summary>
        public static string GetWrapperClassName(Type type)
        {
            // Use a shorter representation for generic types to avoid extremely long file names.
            // type.FullName for generic types includes assembly-qualified names of type arguments,
            // which can exceed Windows path length limits.
            string name;
            if (type.IsGenericType)
            {
                // Build a short name: Namespace.TypeName`N[Arg1,Arg2,...]
                // using only the type name (not assembly-qualified) for each argument
                var genericDef = type.GetGenericTypeDefinition();
                string baseName = genericDef.FullName ?? genericDef.Name;
                var args = type.GetGenericArguments();
                string argStr = string.Join("__", args.Select(a => GetWrapperClassName_TypeShortName(a)));
                name = baseName + "__" + argStr + "__";
            }
            else
            {
                name = type.FullName ?? type.Name;
            }
            var sb = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            return sb.ToString() + "_Wrap";
        }

        private static string GetWrapperClassName_TypeShortName(Type type)
        {
            if (type.IsGenericType)
            {
                var genericDef = type.GetGenericTypeDefinition();
                string baseName = (genericDef.Namespace != null ? genericDef.Namespace + "." : "") + genericDef.Name;
                var args = type.GetGenericArguments();
                string argStr = string.Join("__", args.Select(a => GetWrapperClassName_TypeShortName(a)));
                return baseName + "__" + argStr + "__";
            }
            return (type.Namespace != null ? type.Namespace + "." : "") + type.Name;
        }

        private static string SanitizeMethodName(string name)
        {
            var sb = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            string result = sb.ToString();
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = "_" + result;
            return result;
        }

        private static string EscapeComment(string text)
        {
            if (text == null) return "";
            return text.Replace("\r", "").Replace("\n", " ").Replace("*/", "* /");
        }
    }
}

#endif
