#ifndef JSENGINE_NATIVECLASS_DEFINE
#define JSENGINE_NATIVECLASS_DEFINE                                                                                                                                                                              \
private:                                                                                                                                                                                                         \
    v8::Persistent<v8::FunctionTemplate> GHandlerTemplate;                                                                                                                                                       \
    v8::Persistent<v8::Value> GJSCreateClass;                                                                                                                                                                    \
    v8::Persistent<v8::Value> GJSGetNextClassID;                                                                                                                                                                 \
    v8::Persistent<v8::Value> GJSRegisterProperty;                                                                                                                                                               \
    v8::Persistent<v8::Value> GJSRegisterFunction;                                                                                                                                                               \
    v8::Persistent<v8::Value> GJSNewObject;                                                                                                                                                                      \
    v8::Persistent<v8::Value> GJSGetClass;                                                                                                                                                                       \
    static const char* NativeClassesJS;                                                                                                                                                                          \
    v8::Local<v8::Object> MakeHandler(v8::Local<v8::Context> Context, v8::Puerts::CallbackFunction callback, int64_t Data, bool isStatic);                                                                                      \
public:                                                                                                                                                                                                          \
    void InitNativeClasses(v8::Local<v8::Context> Context);                                                                                                                                                      \
    int RegisterClass(const char *FullName, int BaseTypeId, CSharpConstructorCallback Constructor, CSharpDestructorCallback Destructor, int64_t Data, int Size);                                                 \
    bool RegisterFunction(int ClassID, const char *Name, bool IsStatic, v8::Puerts::CallbackFunction Callback, int64_t Data);                                                                                    \
    bool RegisterProperty(int ClassID, const char *Name, bool IsStatic, v8::Puerts::CallbackFunction Getter, int64_t GetterData, v8::Puerts::CallbackFunction Setter, int64_t SetterData, bool DontDelete);  
#endif