name: download backend (for reusable)

inputs:
  backend:
    description: 'js backend'
    required:
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: test
      run: |
        pwd
        ls -l
      shell: bash

    # read the remote config
    - name: Get backend artifact remote
      run: echo "$(cat unity/native_src/cmake/${{ inputs.backend }}/backend.rc)" >> $GITHUB_ENV
      shell: bash

    # BACKEND_URL is the 1st option.
    - name: wget released artifact
      if: ${{ env.BACKEND_URL != '' && runner.os != 'Windows' }}
      shell: bash
      run: |
        cd unity/native_src
        wget -O backend '${{ env.BACKEND_URL }}'
        tar xzf backend
        rm -rf backend
    - name: wget released artifact
      if: ${{ env.BACKEND_URL != '' && runner.os == 'Windows' }}
      shell: powershell
      run: |
        cd unity\native_src
        Invoke-WebRequest '${{ env.BACKEND_URL }}' -O backend
        tar -xzf backend
        del backend

    # otherwise, download the file in repo/workflow
    - name: Download artifact
      if: ${{ env.BACKEND_URL == '' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        workflow: ${{ env.BACKEND_ARTIFACT_WORKFLOW }}
        name: ${{ env.BACKEND_ARTIFACT_NAME }}
        repo: ${{ env.BACKEND_ARTIFACT_REPO }}
        path: unity/native_src/