name: osx-build

on: 
  push:
    paths: 
      - unity/native_src/**

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd unity/native_src
          chmod 777 make_osx.sh
          ./make_osx.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/native_src/build_osx/Release/puerts.bundle/**/*
          name: Puerts-osx
