name: unity openupm publish

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

env:
  RUNID: 613573412

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish webgl openupm package
        run: |
          git filter-branch --subdirectory-filter unity/Assets/webgl/upm
          git clean -ffdx
          git tag upm/webgl/${{ github.event.inputs.tag_name }}
          git push origin --tag